SaM.ASPApplication/ViewModels/EducationProgramViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SaM.ASPApplication.ViewModels
{
    public class EducationProgramViewModel
    {
        public Guid Guid { get; set; }
        public string Title { get; set; }
        public bool Active { get; set; }
        public string ProgramType { get; set; }
        public string StudyType { get; set; }

        public CategoryViewModel Category { get; set; }

        public EducationTypeViewModel EducationType { get; set; }

        public ICollection<SubjectViewModel> SubjectList { get; set; }
    }
}

SaM.ASPApplication/Areas/Admin/Controllers/EducationProgramController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using SaM.BusinessLogic.AdminFacade;
using Mapster;
using SaM.ASPApplication.Areas.Admin.ViewModels;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace SaM.ASPApplication.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class EducationProgramController : Controller
    {
        EducationProgramFacade logic;        

        public EducationProgramController()
        {
            logic = new EducationProgramFacade();
        }

        public IActionResult Index()
        {
            var result = logic.GetPrograms().Adapt<IEnumerable<ProgramViewModel>>();

            return View(result);
        }

        public IActionResult GetProgram(Guid guid)
        {
            var result = logic.GetProgram(guid).Adapt<ProgramViewModel>();

            return View(result);
        }

        public IActionResult DeleteSubject(Guid guid)
        {
            logic.DeleteSubject(guid);

            return Redirect("Index");
        }

        public IActionResult DeleteProgram(Guid guid)
        {
            logic.DeleteProgram(guid);

            return Redirect("Index");
        }

        public IActionResult ProgramActive(Guid guid, bool isActive)
        {
            logic.ProgramActive(guid, !isActive);

            return Redirect("Index");
        }
    }
}

SaM.ASPApplication/Areas/Admin/Controllers/UpdateProgramsController.cs
using Microsoft.AspNetCore.Mvc;
using SaM.BusinessLogic.AdminFacade;
using System;
using System.Linq;

namespace SaM.ASPApplication.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class UpdateProgramsController : Controller
    {
        EducationProgramFacade logic;

        public UpdateProgramsController()
        {
            logic = new EducationProgramFacade();
        }

        // GET: /<controller>/
        public IActionResult Index()
        {            
            var result = logic.GetPrograms();

            return View(result);
        }

        public IActionResult Update()
        {
            logic.UpdateEducation();
            
            return Redirect("Index");
        }
    }
}

SaM.ASPApplication/Areas/Admin/Views/EducationProgram/GetProgram.cshtml
@model SaM.ASPApplication.Areas.Admin.ViewModels.ProgramViewModel

<h1>Program страница...</h1>

<a asp-action="Index" asp-controller="UpdatePrograms">Онлайн-магазин</a>

<a asp-action="Index">Онлайн-магазин</a>


<h2>@Model.Title</h2>

@foreach (var subj in Model.SubjectList)
{
    <p>
        @subj.Title <br />
        @subj.Certification  |  <a asp-action="DeleteSubject" asp-route-guid="@subj.Guid">Удалить</a>
    </p>
}

SaM.ASPApplication/Areas/Admin/Views/EducationProgram/Index.cshtml
@model IEnumerable<SaM.ASPApplication.Areas.Admin.ViewModels.ProgramViewModel>

<h1>Программы обучения!</h1>

@foreach (var group in Model.GroupBy(g => g.Category))
{
    <h2>@group.Key</h2>

    foreach (var prog in group)
    {
        <p>@prog.Title  <a asp-action="GetProgram" asp-route-guid="@prog.Guid" >View</a> | <a asp-action="DeleteProgram" asp-route-guid="@prog.Guid">Remove</a> | <a asp-action="ProgramActive" asp-route-guid="@prog.Guid" asp-route-isActive="@prog.Active">@prog.Active</a></p>
    }
}